name: "Docs - Release"

on:
  push:
    branches: [main]
    tags:     
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release-docs:
    name: release-docs
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          ref: main # Always checkout main even for tagged releases
          fetch-depth: 0

      - name: 🐳 Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: 🐳 Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🐳 Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}     

      - name: 🐳 Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=raw,value={{sha}}
            type=ref,event=tag,priority=200
            type=raw,value=latest,enable=${{startsWith(github.ref, 'refs/tags/v' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) )}},priority=100,
            type=ref,event=pr,priority=100

      - name: 🐳 Build changed docs
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🐳 Find the primary image tag we just pushed, and output it
        id: image-tag
        run: |
          echo "image-tag=${{ steps.docker_meta.outputs.version }}" >> $GITHUB_OUTPUT
